package com.preyansh.ridesharing.service;

import com.preyansh.ridesharing.dto.DriverRequest;
import com.preyansh.ridesharing.dto.DriverResponse;
import com.preyansh.ridesharing.exception.UserNotFoundException;
import com.preyansh.ridesharing.exception.VehicleNotFoundException;
import com.preyansh.ridesharing.model.Driver;
import com.preyansh.ridesharing.model.User;
import com.preyansh.ridesharing.model.Vehicle;
import com.preyansh.ridesharing.repository.DriverRepository;
import com.preyansh.ridesharing.repository.UserRepository;
import com.preyansh.ridesharing.repository.VehicleRepository;

import org.springframework.stereotype.Service;

// Marks this class as a service component so Spring can manage it
// and inject it into other components, such as DriverController.
@Service
public class DriverService {

    // Repositories used to access Driver, User, and Vehicle records.
    private final DriverRepository driverRepository;
    private final UserRepository userRepository;
    private final VehicleRepository vehicleRepository;

    // Constructor injection: Spring provides the required repositories.
    // final ensures these dependencies cannot be reassigned after initialization.
    public DriverService(
            DriverRepository driverRepository,
            UserRepository userRepository,
            VehicleRepository vehicleRepository) {

        this.driverRepository = driverRepository;
        this.userRepository = userRepository;
        this.vehicleRepository = vehicleRepository;
    }

    // Creates a Driver record using the information supplied by the client.
    // Returns a DTO instead of exposing the Driver entity directly.
    public DriverResponse createDriver(DriverRequest driverRequest) {

        // Find the existing User using the ID supplied in the request.
        // If no User exists, throw an exception handled by GlobalExceptionHandler.
        User user = userRepository.findById(driverRequest.getUserId())
                .orElseThrow(() -> new UserNotFoundException(
                        "User with id " + driverRequest.getUserId() + " not found"
                ));

        // Create a new Driver entity.
        // Its own ID will be generated by the database when it is saved.
        Driver driver = new Driver();

        // Associate the existing User with this Driver.
        // This relationship is persisted through the user_id foreign key.
        driver.setUser(user);

        // Find the existing Vehicle using the ID supplied in the request.
        // If the Vehicle does not exist, throw VehicleNotFoundException.
        Vehicle vehicle = vehicleRepository.findById(driverRequest.getVehicleId())
                .orElseThrow(() -> new VehicleNotFoundException(
                        "Vehicle with id " + driverRequest.getVehicleId() + " not found"
                ));

        // Associate the existing Vehicle with the Driver.
        // This relationship is persisted through the vehicle_id foreign key.
        driver.setVehicle(vehicle);

        // Copy the driver-specific information from the request DTO to the entity.
        driver.setLicenseNumber(driverRequest.getLicenseNumber());
        driver.setStatus(driverRequest.getStatus());

        // Persist the Driver entity and retrieve the saved entity,
        // including its database-generated ID.
        Driver savedDriver = driverRepository.save(driver);

        // Create a response DTO to control which fields the API exposes.
        DriverResponse driverResponse = new DriverResponse();

        // Map the saved entity to the response DTO.
        // Expose the associated User and Vehicle IDs, not their full objects.
        driverResponse.setId(savedDriver.getId());
        driverResponse.setUserId(savedDriver.getUser().getId());
        driverResponse.setLicenseNumber(savedDriver.getLicenseNumber());
        driverResponse.setVehicleId(savedDriver.getVehicle().getId());
        driverResponse.setStatus(savedDriver.getStatus());

        // Return the response DTO to the controller.
        return driverResponse;
    }
}