spring.application.name=ridesharing

spring.datasource.url=jdbc:postgresql://localhost:5432/rideshare
spring.datasource.username=postgres
spring.datasource.password=Bhagwati@99

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true